version: '3.4'

services:
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - /data/db:/data/db
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    
  cache:
    image: redis:alpine
    container_name: redis
    volumes:
      - /data/redis:/data
  
    
  um.users.service:
    image: um.users.service
    container_name: um.users.service
    build:
      context: .
      dockerfile: UsersManagement/TrialsSystem.UsersService/Dockerfile
    depends_on:
      - mongo